#!/usr/bin/env bash

set -e

if [[ $2 = --help ]]; then
  exec "${0##*/}" help "$1"
elif [[ $1 = -* ]] && command -v "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

export FOUNDRY_CACHE=${FOUNDRY_CACHE:-~/.foundry}
export FOUNDRY_CACHE_EXPIRY=${FOUNDRY_CACHE_EXPIRY:-60}
export FOUNDRY_TIMEOUT=${FOUNDRY_TIMEOUT:-10}
export FOUNDRY_MIN_MEDIAN=${FOUNDRY_MIN_MEDIAN:-3}

"${0##*/}-${1-help}" "${@:2}"