#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "==> Setting up DB…"
GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

echo -e ${GREEN}Updating ${RED}forge${GREEN} to ${RED}${REPO}${GREEN} at branch ${RED}${BRANCH}${GREEN}!${NC}

